import { createClientFromRequest } from 'npm:@base44/sdk@0.7.1';
import { format } from "npm:date-fns@3.6.0";

function isValidVolpiEmail(email) {
    if (!email || typeof email !== 'string') return false;
    return email.toLowerCase().endsWith('@volpicapital.com');
}

// Tier 1 triggers that should create follow-up tasks in Affinity
const TIER_1_TASK_TRIGGERS = new Set([
    'ceo_hiring',
    'cfo_hiring',
    'head_of_sales_hiring',
    'head_of_delivery_hiring',
    'executive_hiring',
    'board_member_hired',
    'headcount_growth',
    'financial_results',
    'funding_round',
    'acquisition_announced',
    'international_expansion',
    'new_office_opened',
    'culture_initiative',
    'birthday_reminder',
    'event_participation'
]);

async function pushAlertToAffinity(alert, ownerEmail) {
    const affinityApiKey = Deno.env.get("Affinity_API");
    if (!affinityApiKey) {
        console.log('⚠️ Affinity API key not set, skipping CRM push');
        return { success: false, reason: 'API key not set' };
    }

    // Affinity uses Basic Auth with empty username and API key as password
    const authHeader = 'Basic ' + btoa(':' + affinityApiKey);

    try {
        console.log(`\n🔄 Pushing to Affinity: ${alert.company_name} - ${alert.headline}`);
        
        // Find the organization in Affinity by company name
        const searchResponse = await fetch(
            `https://api.affinity.co/organizations?term=${encodeURIComponent(alert.company_name)}`,
            {
                headers: {
                    'Authorization': authHeader,
                    'Content-Type': 'application/json'
                }
            }
        );

        if (!searchResponse.ok) {
            const errorText = await searchResponse.text();
            console.log(`⚠️ Failed to search Affinity for ${alert.company_name}: ${searchResponse.status} - ${errorText}`);
            return { success: false, reason: `Search failed: ${searchResponse.status}`, error: errorText };
        }

        const searchData = await searchResponse.json();
        
        if (!searchData.organizations || searchData.organizations.length === 0) {
            console.log(`⚠️ Company ${alert.company_name} not found in Affinity`);
            return { success: false, reason: 'Company not found in Affinity' };
        }

        const organizationId = searchData.organizations[0].id;
        console.log(`✅ Found ${alert.company_name} in Affinity (ID: ${organizationId})`);

        // Create note content with clear VOLPI LENS header
        const noteContent = `
═══════════════════════════════════════
🔔 VOLPI LENS ALERT
═══════════════════════════════════════

${alert.headline}

${alert.summary || ''}

📅 Detected: ${format(new Date(alert.detected_date || alert.created_date), "MMMM d, yyyy")}
🏷️ Type: ${alert.trigger_type.replace(/_/g, ' ').toUpperCase()}
⭐ Priority: ${alert.priority.toUpperCase()}
${alert.tier === 'tier_1' ? '🚨 TIER 1 - MUST FOLLOW UP' : ''}

${alert.source_url ? `🔗 Source: ${alert.source_url}` : ''}

${alert.actionable_insight ? `\n💡 Actionable Insight:\n${alert.actionable_insight}` : ''}

${alert.draft_email ? `\n📧 Suggested Outreach:\n${alert.draft_email}` : ''}

───────────────────────────────────────
Alert sent to: ${ownerEmail}
Generated by Volpi Lens Intelligence Platform
`.trim();

        // Add note to organization
        console.log(`📝 Creating note in Affinity for ${alert.company_name}...`);
        const noteResponse = await fetch(
            'https://api.affinity.co/notes',
            {
                method: 'POST',
                headers: {
                    'Authorization': authHeader,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    organization_ids: [organizationId],
                    content: noteContent
                })
            }
        );

        if (noteResponse.ok) {
            const noteData = await noteResponse.json();
            console.log(`✅ Created note in Affinity (ID: ${noteData.id}) for ${alert.company_name}`);
        } else {
            const errorText = await noteResponse.text();
            console.log(`⚠️ Failed to create note for ${alert.company_name}: ${noteResponse.status} - ${errorText}`);
            return { success: false, reason: 'Note creation failed', error: errorText };
        }

        // Create task only for Tier 1 trigger types
        const isTier1Trigger = TIER_1_TASK_TRIGGERS.has(alert.trigger_type);
        if (isTier1Trigger) {
            console.log(`✅ Creating Tier 1 task for ${alert.company_name} (${alert.trigger_type})...`);
            
            const dueDate = new Date();
            dueDate.setDate(dueDate.getDate() + 3); // Due in 3 days

            const taskResponse = await fetch(
                'https://api.affinity.co/tasks',
                {
                    method: 'POST',
                    headers: {
                        'Authorization': authHeader,
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        organization_ids: [organizationId],
                        content: `[VOLPI LENS] Follow up: ${alert.headline}`,
                        due_date: dueDate.toISOString().split('T')[0]
                    })
                }
            );

            if (taskResponse.ok) {
                const taskData = await taskResponse.json();
                console.log(`✅ Created Tier 1 task in Affinity (ID: ${taskData.id}) for ${alert.company_name}`);
                return { success: true, note: true, task: true, task_id: taskData.id };
            } else {
                const errorText = await taskResponse.text();
                console.log(`⚠️ Failed to create task for ${alert.company_name}: ${taskResponse.status} - ${errorText}`);
                return { success: true, note: true, task: false, task_error: errorText };
            }
        } else {
            console.log(`ℹ️ Skipping task creation for ${alert.company_name} - Not a Tier 1 trigger (${alert.trigger_type})`);
            return { success: true, note: true, task: false, task_reason: 'Not Tier 1 trigger' };
        }

    } catch (error) {
        console.error(`❌ Error pushing alert to Affinity for ${alert.company_name}:`, error.message);
        return { success: false, reason: 'Exception', error: error.message };
    }
}

function generateDigestHTML(ownerName, date, alerts, volpiContent) {
    const sortedAlerts = [...alerts].sort((a, b) => {
        if (a.tier === 'tier_1' && b.tier !== 'tier_1') return -1;
        if (a.tier !== 'tier_1' && b.tier === 'tier_1') return 1;
        const dateA = new Date(a.detected_date || a.created_date);
        const dateB = new Date(b.detected_date || b.created_date);
        return dateB.getTime() - dateA.getTime();
    });

    const alertRows = sortedAlerts.map(alert => {
        const tierBadge = alert.tier === 'tier_1' 
            ? '<span style="display: inline-block; background: #dc2626; color: #ffffff; padding: 8px 16px; border-radius: 6px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.8px; box-shadow: 0 2px 4px rgba(220, 38, 38, 0.25);">TIER 1 - MUST FOLLOW UP</span>' 
            : '';
        
        const priorityColors = {
            high: 'background: #dc2626; color: #ffffff;',
            medium: 'background: #f59e0b; color: #ffffff;',
            low: 'background: #3b82f6; color: #ffffff;'
        };

        const priorityBadge = `<span style="display: inline-block; ${priorityColors[alert.priority]} padding: 8px 16px; border-radius: 6px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.8px; margin-left: 8px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.15);">${alert.priority}</span>`;

        const triggerLabel = alert.trigger_type.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
        const triggerBadge = `<span style="display: inline-block; background: #10b981; color: #ffffff; padding: 8px 16px; border-radius: 6px; font-size: 11px; font-weight: 700; letter-spacing: 0.8px; margin-left: 8px; box-shadow: 0 2px 4px rgba(16, 185, 129, 0.25);">${triggerLabel}</span>`;

        const relevantContent = (alert.volpi_content || [])
            .map(url => volpiContent.find(c => c.url === url))
            .filter(Boolean);

        const publishedDate = format(new Date(alert.detected_date || alert.created_date), "d MMM yyyy");
        const detectedDate = format(new Date(alert.created_date), "d MMM yyyy");

        return `
        <div style="background: #ffffff; border: 1px solid #e5e7eb; border-radius: 12px; padding: 32px; margin-bottom: 24px; box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);">
            <div style="margin-bottom: 20px;">
                ${tierBadge}${priorityBadge}${triggerBadge}
            </div>
            
            <h3 style="margin: 0 0 12px 0; font-size: 22px; font-weight: 700; color: #047857; line-height: 1.3;">${alert.company_name}</h3>
            <p style="margin: 0 0 16px 0; font-size: 16px; color: #111827; line-height: 1.6; font-weight: 600;">${alert.headline}</p>
            
            ${alert.summary ? `<p style="margin: 0 0 20px 0; font-size: 15px; color: #374151; line-height: 1.7;">${alert.summary}</p>` : ''}
            
            <div style="margin-bottom: 20px; padding: 16px; background: #f9fafb; border-radius: 8px; border: 1px solid #e5e7eb;">
                <div style="margin-bottom: 8px;">
                    <span style="font-weight: 700; color: #111827; font-size: 14px;">📅 Published:</span> 
                    <span style="color: #374151; font-size: 14px;">${publishedDate}</span>
                    ${alert.date_evidence ? ` <span style="font-size: 12px; color: #6b7280;">(${alert.date_evidence})</span>` : ''}
                </div>
                <div>
                    <span style="font-weight: 700; color: #111827; font-size: 14px;">🔍 Detected:</span> 
                    <span style="color: #374151; font-size: 14px;">${detectedDate}</span>
                    ${alert.source_url ? ` · <a href="${alert.source_url}" style="color: #047857; text-decoration: none; font-weight: 600; font-size: 14px;">View Source →</a>` : ''}
                </div>
            </div>
            
            ${alert.actionable_insight ? `
            <div style="margin-bottom: 20px; padding: 20px; background: #d1fae5; border-left: 4px solid #047857; border-radius: 8px;">
                <p style="margin: 0 0 8px 0; font-size: 12px; font-weight: 700; color: #065f46; text-transform: uppercase; letter-spacing: 0.8px;">💡 ACTIONABLE INSIGHT</p>
                <p style="margin: 0; font-size: 15px; color: #064e3b; line-height: 1.7; font-weight: 500;">${alert.actionable_insight}</p>
            </div>
            ` : ''}
            
            ${alert.draft_email ? `
            <div style="padding: 20px; background: #f1f5f9; border: 1px solid #cbd5e1; border-radius: 8px;">
                <p style="margin: 0 0 12px 0; font-size: 12px; font-weight: 700; color: #0f172a; text-transform: uppercase; letter-spacing: 0.8px;">📧 SUGGESTED OUTREACH</p>
                <pre style="margin: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; font-size: 14px; color: #1e293b; white-space: pre-wrap; line-height: 1.7;">${alert.draft_email}</pre>
            </div>
            ` : ''}
            
            ${relevantContent.length > 0 ? `
            <div style="padding: 20px; background: #f5f3ff; border: 1px solid #e9d5ff; border-radius: 8px; margin-top: 20px;">
                <p style="margin: 0 0 12px 0; font-size: 12px; font-weight: 700; color: #6b21a8; text-transform: uppercase; letter-spacing: 0.8px;">📚 RELEVANT COLLATERAL</p>
                <ul style="margin: 0; padding: 0; list-style: none;">
                    ${relevantContent.map(c => `<li style="margin-bottom: 8px;"><a href="${c.url}" style="color: #7c3aed; text-decoration: none; font-size: 14px; font-weight: 600;">→ ${c.title}</a></li>`).join('')}
                </ul>
            </div>
            ` : ''}
        </div>
        `;
    }).join('');

    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body { 
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; 
                margin: 0; 
                padding: 0; 
                background-color: #f3f4f6;
            }
            @media only screen and (max-width: 600px) {
                .container { width: 100% !important; padding: 16px !important; }
                .logo { max-width: 140px !important; }
                .content-padding { padding: 24px 20px !important; }
            }
        </style>
    </head>
    <body style="background-color: #f3f4f6; padding: 20px 0;">
        <div class="container" style="max-width: 680px; margin: 0 auto; background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);">
            
            <!-- Header with Volpi Branding -->
            <div style="background: linear-gradient(135deg, #047857 0%, #065f46 100%); padding: 48px 40px; text-align: center;">
                <img src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68f5e8c214c862c9e823b068/21277dc16_volpi.png" alt="Volpi Capital" class="logo" style="max-width: 180px; height: auto; margin-bottom: 24px; filter: brightness(0) invert(1);" />
                <h1 style="margin: 0 0 8px 0; font-size: 28px; font-weight: 700; color: #ffffff; letter-spacing: -0.5px; line-height: 1.2;">Volpi Lens Intelligence Digest</h1>
                <p style="margin: 0; font-size: 16px; color: #ffffff; font-weight: 600; letter-spacing: 0.3px;">${date}</p>
            </div>
            
            <!-- Main Content -->
            <div class="content-padding" style="padding: 40px 36px; background-color: #ffffff;">
                <p style="margin: 0 0 24px 0; font-size: 17px; color: #111827; line-height: 1.6;">Hi <strong style="color: #047857;">${ownerName}</strong>,</p>
                <p style="margin: 0 0 32px 0; font-size: 15px; color: #374151; line-height: 1.7;">Here are your latest intelligence alerts from Volpi Lens:</p>
                
                ${alertRows}
            </div>
            
            <!-- Footer with Volpi Branding -->
            <div style="background: #d1fae5; padding: 32px 40px; text-align: center; border-top: 2px solid #10b981;">
                <img src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68f5e8c214c862c9e823b068/21277dc16_volpi.png" alt="Volpi Capital" style="max-width: 140px; height: auto; margin-bottom: 16px; opacity: 0.85;" />
                <p style="margin: 0 0 6px 0; font-size: 15px; color: #065f46; font-weight: 700; letter-spacing: 0.3px;">Volpi Capital</p>
                <p style="margin: 0 0 12px 0; font-size: 13px; color: #047857; font-weight: 500;">Private Equity Intelligence Platform</p>
                <a href="https://volpicapital.com" style="color: #047857; text-decoration: none; font-size: 13px; font-weight: 600; letter-spacing: 0.3px;">volpicapital.com</a>
            </div>
            
        </div>
    </body>
    </html>
    `;
}

Deno.serve(async (req) => {
    try {
        const base44 = createClientFromRequest(req);
        
        const thirtyDaysAgo = new Date();
        thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
        
        const allPotentialAlerts = await base44.asServiceRole.entities.Alert.filter({
            status: 'new',
            created_date: { $gte: thirtyDaysAgo.toISOString() }
        });

        if (allPotentialAlerts.length === 0) {
            return Response.json({
                success: true,
                message: 'No new alerts to send from the last 30 days',
                digests_sent: 0
            });
        }

        const companyIds = [...new Set(allPotentialAlerts.map(a => a.company_id))];
        const companies = await base44.asServiceRole.entities.Company.filter({
            id: { $in: companyIds }
        });

        const volpiContent = await base44.asServiceRole.entities.VolpiContent.list();

        const today = new Date();
        const isWeeklySendDay = today.getDay() === 1;

        const alertsByOwner = {};
        const ownersSkippedWeekly = new Set();
        
        console.log(`\n📊 Processing ${allPotentialAlerts.length} potential alerts...`);
        
        for (const alert of allPotentialAlerts) {
            const company = companies.find(c => c.id === alert.company_id);
            if (!company) {
                console.log(`⚠️ Alert ${alert.id}: Company not found (${alert.company_id})`);
                continue;
            }

            const owners = company.relationship_owners || [];
            console.log(`\n📍 Alert for ${company.name}: ${owners.length} owner(s) - "${alert.headline}"`);
            
            for (const owner of owners) {
                if (!owner.email) {
                    console.log(`  ⚠️ Owner missing email: ${owner.name || 'unknown'}`);
                    continue;
                }
                
                if (!isValidVolpiEmail(owner.email)) {
                    console.log(`  ⚠️ Skipping non-Volpi email: ${owner.email}`);
                    continue;
                }

                const digestFrequency = owner.digest_frequency || 'daily';
                
                if (digestFrequency === 'weekly' && !isWeeklySendDay) {
                    console.log(`  ⏭️ Skipping ${owner.email} - weekly digest not due today`);
                    ownersSkippedWeekly.add(owner.email);
                    continue;
                }
                
                if (alert.sent_to && alert.sent_to.includes(owner.email)) {
                    console.log(`  ⏭️ Already sent to ${owner.email}`);
                    continue;
                }

                if (alert.discarded_for && alert.discarded_for.includes(owner.email)) {
                    console.log(`  ⏭️ Discarded for ${owner.email}`);
                    continue;
                }
                
                console.log(`  ✓ Queuing for ${owner.email} (${digestFrequency})`);
                
                if (!alertsByOwner[owner.email]) {
                    alertsByOwner[owner.email] = {
                        name: owner.name || owner.email.split('@')[0],
                        alertsByCompany: {},
                        digestFrequency: digestFrequency
                    };
                }
                
                if (!alertsByOwner[owner.email].alertsByCompany[company.id]) {
                    alertsByOwner[owner.email].alertsByCompany[company.id] = [];
                }
                
                alertsByOwner[owner.email].alertsByCompany[company.id].push(alert);
            }
        }

        console.log(`\n📧 Preparing to send digests to ${Object.keys(alertsByOwner).length} owner(s)`);

        const results = [];
        const dateStr = format(new Date(), 'do MMMM yyyy');
        const affinityResults = { notes_created: 0, tasks_created: 0, failures: 0 };

        for (const [ownerEmail, data] of Object.entries(alertsByOwner)) {
            try {
                if (!isValidVolpiEmail(ownerEmail)) {
                    console.log(`⚠️ Blocked attempt to send to non-Volpi email: ${ownerEmail} (final check)`);
                    results.push({
                        owner: ownerEmail,
                        status: 'blocked',
                        reason: 'Non-Volpi email address'
                    });
                    continue;
                }

                const allAlertsForOwner = [];
                const seenAlertIds = new Set();
                
                for (const [companyId, companyAlerts] of Object.entries(data.alertsByCompany)) {
                    const sortedAlerts = companyAlerts.sort((a, b) => {
                        if (a.tier === 'tier_1' && b.tier !== 'tier_1') return -1;
                        if (a.tier !== 'tier_1' && b.tier === 'tier_1') return 1;
                        return new Date(b.created_date).getTime() - new Date(a.created_date).getTime();
                    });
                    
                    const limitedAlerts = sortedAlerts.slice(0, 2);
                    
                    for (const alert of limitedAlerts) {
                        if (!seenAlertIds.has(alert.id)) {
                            seenAlertIds.add(alert.id);
                            allAlertsForOwner.push(alert);
                        }
                    }
                }

                if (allAlertsForOwner.length === 0) {
                    console.log(`ℹ️ No new, unsent alerts found for ${ownerEmail} after deduplication and filtering.`);
                    continue;
                }

                console.log(`\n📨 Sending to ${ownerEmail}: ${allAlertsForOwner.length} alert(s)`);

                const htmlBody = generateDigestHTML(
                    data.name,
                    dateStr,
                    allAlertsForOwner,
                    volpiContent
                );

                const digestType = data.digestFrequency === 'weekly' ? 'Weekly' : 'Daily';
                const subjectLine = `Your ${digestType} Volpi Lens Digest — ${dateStr}`;

                await base44.asServiceRole.integrations.Core.SendEmail({
                    to: ownerEmail,
                    subject: subjectLine,
                    body: htmlBody,
                    from_name: 'Volpi Capital'
                });

                console.log(`\n🔄 Pushing ${allAlertsForOwner.length} alerts to Affinity CRM...`);
                
                // Push alerts to Affinity CRM (only for sent digest alerts)
                for (const alert of allAlertsForOwner) {
                    const affinityResult = await pushAlertToAffinity(alert, ownerEmail);
                    
                    if (affinityResult.success) {
                        if (affinityResult.note) affinityResults.notes_created++;
                        if (affinityResult.task) affinityResults.tasks_created++;
                    } else {
                        affinityResults.failures++;
                    }
                }

                for (const alert of allAlertsForOwner) {
                    const currentSentTo = alert.sent_to || [];
                    const updatedSentTo = [...new Set([...currentSentTo, ownerEmail])];

                    await base44.asServiceRole.entities.Alert.update(alert.id, {
                        sent_to: updatedSentTo
                    });
                }

                results.push({
                    owner: ownerEmail,
                    alerts_sent: allAlertsForOwner.length,
                    status: 'sent'
                });

                console.log(`✅ Sent ${digestType} digest to ${ownerEmail} with ${allAlertsForOwner.length} alerts`);

            } catch (error) {
                console.error(`❌ Failed to send digest to ${ownerEmail}:`, error.message);
                results.push({
                    owner: ownerEmail,
                    status: 'failed',
                    error: error.message
                });
            }
        }

        console.log(`\n✅ Digest sending complete!`);
        console.log(`   - Sent: ${results.filter(r => r.status === 'sent').length}`);
        console.log(`   - Blocked: ${results.filter(r => r.status === 'blocked').length}`);
        console.log(`   - Failed: ${results.filter(r => r.status === 'failed').length}`);
        console.log(`   - Skipped (weekly): ${ownersSkippedWeekly.size}`);
        console.log(`\n📊 Affinity CRM Results:`);
        console.log(`   - Notes created: ${affinityResults.notes_created}`);
        console.log(`   - Tasks created: ${affinityResults.tasks_created}`);
        console.log(`   - Failures: ${affinityResults.failures}`);

        return Response.json({
            success: true,
            digests_sent: results.filter(r => r.status === 'sent').length,
            blocked_emails: results.filter(r => r.status === 'blocked').length,
            skipped_weekly_users: ownersSkippedWeekly.size,
            total_alerts_processed_for_owners: allPotentialAlerts.length,
            is_weekly_send_day: isWeeklySendDay,
            affinity_integration: affinityResults,
            results
        });

    } catch (error) {
        console.error('❌ Daily digest error:', error);
        return Response.json({ 
            error: error.message 
        }, { status: 500 });
    }
});