import { createClientFromRequest } from 'npm:@base44/sdk@0.7.1';
import { format } from "npm:date-fns@3.6.0";

function isValidVolpiEmail(email) {
    if (!email || typeof email !== 'string') return false;
    return email.toLowerCase().endsWith('@volpicapital.com');
}

const TIER_1_TASK_TRIGGERS = new Set([
    'ceo_hiring', 'cfo_hiring', 'head_of_sales_hiring', 'head_of_delivery_hiring',
    'executive_hiring', 'board_member_hired', 'headcount_growth', 'financial_results',
    'funding_round', 'acquisition_announced', 'international_expansion', 
    'new_office_opened', 'culture_initiative', 'birthday_reminder', 'event_participation'
]);

async function pushAlertToAffinity(alert, ownerEmail, base44) {
    const affinityApiKey = Deno.env.get("Affinity_API");
    if (!affinityApiKey) return { success: false, reason: 'API key not set' };

    // Skip if already synced to Affinity
    if (alert.affinity_synced) {
        console.log(`⏭️ Skipping ${alert.company_name} - already synced to Affinity`);
        return { success: true, skipped: true, reason: 'Already synced' };
    }

    const authHeader = 'Basic ' + btoa(':' + affinityApiKey);

    try {
        console.log(`🔄 Pushing to Affinity: ${alert.company_name}`);
        
        const searchResponse = await fetch(
            `https://api.affinity.co/organizations?term=${encodeURIComponent(alert.company_name)}`,
            { headers: { 'Authorization': authHeader, 'Content-Type': 'application/json' } }
        );

        if (!searchResponse.ok) return { success: false, reason: 'Search failed' };

        const searchData = await searchResponse.json();
        if (!searchData.organizations?.length) return { success: false, reason: 'Company not found' };

        const organizationId = searchData.organizations[0].id;

        const noteContent = `
═══════════════════════════════════════
🔔 VOLPI LENS ALERT
═══════════════════════════════════════

${alert.headline}

${alert.summary || ''}

📅 Detected: ${format(new Date(alert.detected_date || alert.created_date), "MMMM d, yyyy")}
🏷️ Type: ${alert.trigger_type.replace(/_/g, ' ').toUpperCase()}
⭐ Priority: ${alert.priority.toUpperCase()}
${alert.tier === 'tier_1' ? '🚨 TIER 1 - MUST FOLLOW UP' : ''}

${alert.source_url ? `🔗 Source: ${alert.source_url}` : ''}

${alert.actionable_insight ? `\n💡 Actionable Insight:\n${alert.actionable_insight}` : ''}

${alert.draft_email ? `\n📧 Suggested Outreach:\n${alert.draft_email}` : ''}

───────────────────────────────────────
Alert sent to: ${ownerEmail}
Generated by Volpi Lens Intelligence Platform
`.trim();

        const noteResponse = await fetch('https://api.affinity.co/notes', {
            method: 'POST',
            headers: { 'Authorization': authHeader, 'Content-Type': 'application/json' },
            body: JSON.stringify({ organization_ids: [organizationId], content: noteContent })
        });

        if (!noteResponse.ok) return { success: false, reason: 'Note creation failed' };

        if (TIER_1_TASK_TRIGGERS.has(alert.trigger_type)) {
            const dueDate = new Date();
            dueDate.setDate(dueDate.getDate() + 3);

            const taskResponse = await fetch('https://api.affinity.co/tasks', {
                method: 'POST',
                headers: { 'Authorization': authHeader, 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    organization_ids: [organizationId],
                    content: `[VOLPI LENS] Follow up: ${alert.headline}`,
                    due_date: dueDate.toISOString().split('T')[0]
                })
            });

            if (taskResponse.ok) {
                // Mark as synced
                await base44.asServiceRole.entities.Alert.update(alert.id, {
                    affinity_synced: true,
                    affinity_synced_date: new Date().toISOString()
                });
            }
            return { success: true, note: true, task: taskResponse.ok };
        }

        // Mark as synced (note was created)
        await base44.asServiceRole.entities.Alert.update(alert.id, {
            affinity_synced: true,
            affinity_synced_date: new Date().toISOString()
        });
        
        return { success: true, note: true, task: false };
    } catch (error) {
        return { success: false, reason: error.message };
    }
}

function generateDigestHTML(ownerName, date, alerts, volpiContent) {
    const sortedAlerts = [...alerts].sort((a, b) => {
        if (a.tier === 'tier_1' && b.tier !== 'tier_1') return -1;
        if (a.tier !== 'tier_1' && b.tier === 'tier_1') return 1;
        const dateA = new Date(a.detected_date || a.created_date);
        const dateB = new Date(b.detected_date || b.created_date);
        return dateB.getTime() - dateA.getTime();
    });

    const alertRows = sortedAlerts.map(alert => {
        const tierBadge = alert.tier === 'tier_1' 
            ? '<span style="display: inline-block; background: #dc2626; color: white; padding: 8px 14px; border-radius: 6px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; box-shadow: 0 2px 4px rgba(220, 38, 38, 0.3);">TIER 1 - MUST FOLLOW UP</span>' 
            : '';
        
        const priorityColors = {
            high: 'background: #dc2626; color: white; box-shadow: 0 2px 4px rgba(220, 38, 38, 0.3);',
            medium: 'background: #f59e0b; color: white; box-shadow: 0 2px 4px rgba(245, 158, 11, 0.3);',
            low: 'background: #3b82f6; color: white; box-shadow: 0 2px 4px rgba(59, 130, 246, 0.3);'
        };

        const priorityBadge = `<span style="display: inline-block; ${priorityColors[alert.priority]} padding: 8px 14px; border-radius: 6px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; margin-left: 8px;">${alert.priority}</span>`;

        const triggerLabel = alert.trigger_type.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
        const triggerBadge = `<span style="display: inline-block; background: #10b981; color: white; padding: 8px 14px; border-radius: 6px; font-size: 11px; font-weight: 600; letter-spacing: 0.5px; margin-left: 8px; box-shadow: 0 2px 4px rgba(16, 185, 129, 0.3);">${triggerLabel}</span>`;

        const relevantContent = (alert.volpi_content || [])
            .map(url => volpiContent.find(c => c.url === url))
            .filter(Boolean);

        const publishedDate = format(new Date(alert.detected_date || alert.created_date), "d MMM yyyy");
        const detectedDate = format(new Date(alert.created_date), "d MMM yyyy");

        return `
        <div style="background: #ffffff; border: 2px solid #e5e7eb; border-radius: 12px; padding: 32px; margin-bottom: 28px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);">
            <div style="margin-bottom: 18px;">
                ${tierBadge}${priorityBadge}${triggerBadge}
            </div>
            
            <h3 style="margin: 0 0 14px 0; font-size: 24px; font-weight: 700; color: #059669; line-height: 1.3;">${alert.company_name}</h3>
            <p style="margin: 0 0 18px 0; font-size: 17px; color: #1f2937; line-height: 1.6; font-weight: 500;">${alert.headline}</p>
            
            ${alert.summary ? `<p style="margin: 0 0 18px 0; font-size: 15px; color: #4b5563; line-height: 1.7;">${alert.summary}</p>` : ''}
            
            <div style="display: flex; flex-direction: column; gap: 8px; margin-bottom: 22px; font-size: 14px; color: #6b7280; padding: 16px; background: #f9fafb; border-radius: 8px;">
                <div>
                    <span style="font-weight: 700; color: #1f2937;">📅 Published:</span> <span style="color: #374151;">${publishedDate}</span>
                    ${alert.date_evidence ? ` <span style="font-size: 12px; color: #9ca3af;">(${alert.date_evidence})</span>` : ''}
                </div>
                <div>
                    <span style="font-weight: 700; color: #1f2937;">🔍 Detected:</span> <span style="color: #374151;">${detectedDate}</span>
                    ${alert.source_url ? ` · <a href="${alert.source_url}" style="color: #059669; text-decoration: none; font-weight: 600;">View Source →</a>` : ''}
                </div>
            </div>
            
            ${alert.actionable_insight ? `
            <div style="margin-bottom: 22px; padding: 22px; background: #ecfdf5; border-left: 4px solid #059669; border-radius: 8px; box-shadow: 0 2px 4px rgba(5, 150, 105, 0.1);">
                <p style="margin: 0 0 10px 0; font-size: 13px; font-weight: 700; color: #047857; text-transform: uppercase; letter-spacing: 0.5px;">💡 Actionable Insight</p>
                <p style="margin: 0; font-size: 15px; color: #065f46; line-height: 1.7; font-weight: 500;">${alert.actionable_insight}</p>
            </div>
            ` : ''}
            
            ${alert.draft_email ? `
            <div style="padding: 22px; background: #f8fafc; border: 2px solid #e2e8f0; border-radius: 8px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);">
                <p style="margin: 0 0 14px 0; font-size: 13px; font-weight: 700; color: #1e293b; text-transform: uppercase; letter-spacing: 0.5px;">📧 Suggested Outreach</p>
                <pre style="margin: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; font-size: 15px; color: #334155; white-space: pre-wrap; line-height: 1.8;">${alert.draft_email}</pre>
            </div>
            ` : ''}
            
            ${relevantContent.length > 0 ? `
            <div style="padding: 22px; background: #faf5ff; border: 2px solid #e9d5ff; border-radius: 8px; margin-top: 22px; box-shadow: 0 2px 4px rgba(168, 85, 247, 0.1);">
                <p style="margin: 0 0 14px 0; font-size: 13px; font-weight: 700; color: #7c3aed; text-transform: uppercase; letter-spacing: 0.5px;">📚 Relevant Collateral</p>
                <ul style="margin: 0; padding: 0; list-style: none;">
                    ${relevantContent.map(c => `<li style="margin-bottom: 10px;"><a href="${c.url}" style="color: #7c3aed; text-decoration: none; font-size: 15px; font-weight: 600;">→ ${c.title}</a></li>`).join('')}
                </ul>
            </div>
            ` : ''}
        </div>
        `;
    }).join('');

    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 0; }
            @media only screen and (max-width: 600px) {
                .container { width: 100% !important; padding: 16px !important; }
                .logo { max-width: 120px !important; }
            }
        </style>
    </head>
    <body style="background-color: #f3f4f6; padding: 20px;">
        <div class="container" style="max-width: 700px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);">
            <div style="background: linear-gradient(135deg, #059669 0%, #047857 100%); color: #ffffff; padding: 44px 36px; text-align: center;">
                <img src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68f5e8c214c862c9e823b068/21277dc16_volpi.png" alt="Volpi Capital" class="logo" style="max-width: 200px; height: auto; margin-bottom: 24px;" />
                <h1 style="margin: 0 0 10px 0; font-size: 32px; font-weight: 700; letter-spacing: -0.5px;">Volpi Lens Intelligence Digest</h1>
                <p style="margin: 0; font-size: 18px; color: #d1fae5; font-weight: 500;">${date}</p>
            </div>
            
            <div style="padding: 44px 36px;">
                <p style="margin: 0 0 28px 0; font-size: 18px; color: #1f2937; line-height: 1.6;">Hi <strong style="color: #059669;">${ownerName}</strong>,</p>
                <p style="margin: 0 0 36px 0; font-size: 16px; color: #4b5563; line-height: 1.7;">Here are your latest intelligence alerts from Volpi Lens:</p>
                
                ${alertRows}
            </div>
            
            <div style="background: #ecfdf5; padding: 36px; text-align: center; border-top: 3px solid #10b981;">
                <img src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/68f5e8c214c862c9e823b068/21277dc16_volpi.png" alt="Volpi Capital" style="max-width: 160px; height: auto; margin-bottom: 18px; opacity: 0.9;" />
                <p style="margin: 0 0 10px 0; font-size: 16px; color: #047857; font-weight: 700;">Volpi Capital</p>
                <p style="margin: 0; font-size: 13px; color: #065f46;">Private Equity Intelligence Platform</p>
                <p style="margin: 14px 0 0 0;"><a href="https://volpicapital.com" style="color: #059669; text-decoration: none; font-size: 14px; font-weight: 600;">volpicapital.com</a></p>
            </div>
        </div>
    </body>
    </html>
    `;
}

Deno.serve(async (req) => {
    try {
        const base44 = createClientFromRequest(req);
        const user = await base44.auth.me();
        
        if (!user || user.role !== 'admin') {
            return Response.json({ error: 'Unauthorized - Admin only' }, { status: 401 });
        }

        const { owner_email, batch_date } = await req.json();
        
        console.log(`📧 Resending digest to: ${owner_email}${batch_date ? ` for batch: ${batch_date}` : ''}`);
        
        if (!owner_email) {
            return Response.json({ error: 'owner_email required' }, { status: 400 });
        }

        // Validate email domain
        if (!isValidVolpiEmail(owner_email)) {
            console.log(`⚠️ BLOCKED: Invalid email domain: ${owner_email}`);
            return Response.json({ 
                error: 'Invalid email domain. Only @volpicapital.com addresses allowed.',
                blocked_email: owner_email
            }, { status: 403 });
        }

        // Get ALL alerts that were sent to this owner
        const allAlerts = await base44.asServiceRole.entities.Alert.list('-created_date');

        // Filter for alerts sent to this owner
        const ownerAlerts = allAlerts.filter(alert => 
            alert.sent_to && alert.sent_to.includes(owner_email)
        );

        console.log(`📊 Found ${ownerAlerts.length} total alerts ever sent to ${owner_email}`);

        if (ownerAlerts.length === 0) {
            return Response.json({
                success: true,
                message: `No sent alerts found for ${owner_email}`,
                alerts_sent: 0
            });
        }

        let batchAlerts;

        if (batch_date) {
            // User is resending a SPECIFIC digest batch from Digest History
            const targetDate = new Date(batch_date);
            const targetDateKey = `${targetDate.getFullYear()}-${targetDate.getMonth()}-${targetDate.getDate()}`;
            
            console.log(`🎯 Looking for specific batch: ${targetDateKey}`);
            
            batchAlerts = ownerAlerts.filter(alert => {
                const alertDate = new Date(alert.created_date);
                const alertDateKey = `${alertDate.getFullYear()}-${alertDate.getMonth()}-${alertDate.getDate()}`;
                return alertDateKey === targetDateKey;
            });

            console.log(`📦 Found ${batchAlerts.length} alerts in this specific batch`);
        } else {
            // No specific batch - use most recent batch (legacy behavior)
            const alertsByDate = {};
            ownerAlerts.forEach(alert => {
                const alertDate = new Date(alert.created_date);
                const dateKey = `${alertDate.getFullYear()}-${alertDate.getMonth()}-${alertDate.getDate()}`;
                
                if (!alertsByDate[dateKey]) {
                    alertsByDate[dateKey] = [];
                }
                alertsByDate[dateKey].push(alert);
            });

            const dates = Object.keys(alertsByDate).sort().reverse();
            const mostRecentDate = dates[0];
            batchAlerts = alertsByDate[mostRecentDate];

            console.log(`📦 Using most recent batch: ${mostRecentDate} with ${batchAlerts.length} alerts`);
        }

        if (batchAlerts.length === 0) {
            return Response.json({
                success: true,
                message: `No alerts found in the specified batch`,
                alerts_sent: 0
            });
        }

        // Get companies to find owner name
        const companies = await base44.asServiceRole.entities.Company.list();
        let ownerName = owner_email.split('@')[0];
        
        for (const company of companies) {
            const owners = company.relationship_owners || [];
            const matchingOwner = owners.find(o => o.email === owner_email);
            if (matchingOwner && matchingOwner.name) {
                ownerName = matchingOwner.name;
                break;
            }
        }

        // Get Volpi content
        const volpiContent = await base44.asServiceRole.entities.VolpiContent.list();

        const dateStr = format(new Date(), 'do MMMM yyyy');
        const htmlBody = generateDigestHTML(ownerName, dateStr, batchAlerts, volpiContent);

        console.log(`📤 Sending digest with ${batchAlerts.length} alerts to ${owner_email}...`);

        // Send email
        await base44.asServiceRole.integrations.Core.SendEmail({
            to: owner_email,
            subject: `Your Volpi Lens Digest — ${dateStr}`,
            body: htmlBody,
            from_name: 'Volpi Capital'
        });

        // Push to Affinity
        console.log(`🔄 Pushing ${batchAlerts.length} alerts to Affinity...`);
        const affinityResults = { notes: 0, tasks: 0, failures: 0 };

        for (const alert of batchAlerts) {
            const result = await pushAlertToAffinity(alert, owner_email, base44);
            if (result.success) {
                if (result.skipped) {
                    // Already synced, don't count
                } else {
                    if (result.note) affinityResults.notes++;
                    if (result.task) affinityResults.tasks++;
                }
            } else {
                affinityResults.failures++;
            }
        }

        console.log(`✅ Digest resent with Affinity push: ${affinityResults.notes} notes, ${affinityResults.tasks} tasks`);

        return Response.json({
            success: true,
            alerts_sent: batchAlerts.length,
            owner: owner_email,
            batch_date: batch_date || 'most recent',
            affinity_integration: affinityResults
        });

    } catch (error) {
        console.error('❌ Resend error:', error);
        return Response.json({ 
            error: error.message,
            stack: error.stack 
        }, { status: 500 });
    }
});